server:
  port: 3100

spring:
  application:
    name: config-server

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nineeko/project-configs2
          default-label: main
          search-paths:
            - configs/common
            - configs/{application}/{profile}
            - configs/{application}


eureka:
  instance:
    prefer-ip-address: false
    hostname: host.docker.internal

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:3150/eureka/